### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by iLoveTux** [juancarlospaco/timetracker#1]
## EDIT

I am mistaken.

I had thought that I had tracked it down, but the problem came from dependencies just like @juancarlospaco said in the comment below. I needed to install pykde4.

There is, however, a discrepancy in the version available through Ninja-IDE plugin manager and what is available at github. I should have checked the version before looking at the code (That's where I got confused) in version 0.1 the error doesn't say that you need PyKDE (in version 0.2 it does). I guess that I will need to keep an eye on the versions for these plugins.

---

Before I begin:
- Fedora 21
- intel core i5 quad core
- 8 GB RAM
- GNOME 3

When I install your addin in Ninja-IDE it installs fine, but when I go into the GUI for the timetracker addin it complains that I need kTimeTracker app installed, so I issue the command

```
$ sudo yum install ktimetracker
```

After yum installs everything (a lot of KDE dependencies) it seems as though everything is fine, but going back to the timetracker addin it still complains about needing to install the kTimeTracker app.

Now, the problem is that in main.py on line 55-56 it assumes that the directory "~/.kde/share/apps/ktimetracker" exists and that this is where a file called "ktimetracker.ics" either exists or can be created. I corrected the issue simply by creating the directory structure.

This may be a bug in the package that Fedora provides (perhaps it should create the directory structure), or this could be a bug in main.py on line 83 when you catch all exceptions.

The way I see it there are four ways to tackle this problem (and if you want I can turn this into a pull request, but I don't know which route you would want to go).
1. Submit a bug report upstream to the kTimeTracker team (I don't really recommend this route, because I don't believe that every application installed should create a "dot" directory in everyone's home directory)
2. Check for the existence of the required directory and create it if needed (I don't recommend this route either because then you cannot be sure that the package is installed)
3. On line 83, when you catch the exception perhaps you can grab a reference to the exception and perhaps provide more information about this particular exception. Something like the code block at the end of my issue here (and remember if you want I can turn this into a pull request) Now this would've pointed me in the right direction. A stack trace could also be useful, but there is some circular reference magic which I keep hitting.
4. In the README.md you could put a note (perhaps a "Known Issues" section) telling users that you may need to create this directory structure (I could also turn this into a pull request)

Anyway, Thank you so much for all of your hard work on Ninja-IDE I use your addins all the time.

**_The code example for option 3**_

``` python
    except Exception as e:
        self.dock.setWidget(QLabel(""" <center> <h3>ಠ_ಠ<br>
            ERROR: {}!
            Perhaps you should install kTimeTracker and PyKDE ! </h3><br>
            <br><i> (Sorry, cant embed non-Qt Apps). </i><center>""".format(str(e))))
```

**Comment by ghost** [comment]
The solution is provided right there, on the text you are quoting, you need
PyKDE.
For python2 kde4.
:)

**Comment by iLoveTux** [comment]
So this is good to close. It was a dependency issue on my part, but perhaps we can get this latest version available from Ninja-IDE (I'm not sure how much work this is, but I would be happy to help)
